resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:jamesmcallister/houseprices.git
    branch: concourse
    private_key: {{private_key}}

- name: pipeline-worker
  type: docker-image
  source:
    repository: "172.17.0.2:5000/pipeline-worker"
    insecure_registries: ["172.17.0.2:5000"]

jobs:
- name: main
  plan:
  - get: source-code
  - put: pipeline-worker
    params:
      build: source-code

- name: total
  plan:
  - get: source-code
  - get: pipeline-worker
  - task: hello
    config:
      platform: linux
      image: pipeline-worker
      inputs:
      - name: source-code
      run:
        path: echo
        args:
        - hello world

