resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:jamesmcallister/houseprices.git
    branch: concourse
    private_key: {{private_key}}

- name: worker-source-code
  type: git
  source:
    uri: git@github.com:jamesmcallister/houseprices.git
    branch: concourse
    private_key: {{private_key}}
  paths:
  - "docker/worker"

- name: pipeline-worker
  type: docker-image
  source:
    repository: "concourse-registry:5000/pipeline-worker"
    insecure_registries: ["concourse-registry:5000"]


- name: mc
  type: docker-image
  source:
    repository: "concourse-registry:5000/mc"
    insecure_registries: ["concourse-registry:5000"]

jobs:
- name: nodejs-worker-build
  serial: true
  plan:
  - get: worker-source-code
    trigger: true
  - put: pipeline-worker
    params:
      build: worker-source-code/docker/worker

- name: mc
  plan:
  - get: source-code
  - put: mc
    params:
      build: source-code/docker/mc

- name: minio-test
  plan:
  - get: mc
  - task: say-hello
    image: mc
    config:
      platform: linux
      run:
        path: mc
        args:
        - ls
        - minio

- name: hello-world-2
  plan:
  - get: pipeline-worker
  - get: source-code
  - task: say-hello
    image: pipeline-worker
    config:
      platform: linux
      inputs:
        - name: source-code
      run:
        path: bash
        args:
        - -exc
        - |
          . ~/.bashrc
          pushd source-code
            npm install -DE
            npm run test
          popd
