resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:jamesmcallister/houseprices.git
    branch: concourse
    private_key: {{private_key}}

- name: pipeline-worker
  type: docker-image
  source:
    repository: "concourse-registry:5000/pipeline-worker"
    insecure_registries: ["concourse-registry:5000"]

jobs:
- name: main
  plan:
  - get: source-code
  - put: pipeline-worker
    params:
      build: source-code

- name: hello-world-2
  plan:
  - get: pipeline-worker
    passed: [main]
  - get: source-code
  - task: say-hello
    config:
      platform: linux
      image: pipeline-worker
      run:
        path: echo
        args: ["Hello, world!"]

