# This is a service gateway to the replica set created by the deployment.
# Take a look at the deployment.yaml for general notes about this chart.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dockerInfluxDbDns }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: ClusterIP
  ports:
  - port: {{default 8086 .Values.httpPort}}
    targetPort: 8086
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-influxdb-deployment
