---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-minio-deployment
  labels:
    app: {{ .Release.Name }}-minio-deployment
spec:
  containers:
    - name: minio
      image: minio/minio:RELEASE.2017-05-05T01-14-51Z
      ports:
        - containerPort: 9000
