---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-registry-deployment
  labels:
    app: {{ .Release.Name }}-registry-deployment
spec:
  containers:
    - name: docker-registry
      image: registry
      ports:
        - containerPort: 5000
