---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-registry-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-registry-deployment
    spec:
      containers:
        - name: docker-registry
          image: registry
          ports:
            - containerPort: 5000
