task: fetch-node-cache
image: mc
config:
  platform: linux
  outputs:
    - name: npmcache-in
  run:
    path: sh
    args:
    - -exc
    - |
      mc cp --recursive minio/npmcache fetched
      mv fetched/npmcache/* npmcache-in