task: pull-request
image: pipeline-worker
config:
  platform: linux
  inputs:
    - name: git-pull-requests
    - name: npmcache-in
  outputs:
    - name: npmcache-out
  run:
    path: bash
    args:
    - -exc
    - |
      . ~/.bashrc
      pushd git-pull-requests
        mkdir node_modules
        mkdir ~/.npm
        tar xzf ../npmcache-in/npmcache.tar.gz -C node_modules
        tar xzf ../npmcache-in/npm.tar.gz -C ~/.npm
        npm install -DE
        npm run unit
        npm run int
        tar czf ../npmcache-out/npmcache.tar.gz -C node_modules .
        tar czf ../npmcache-out/npm.tar.gz -C ~/.npm .
      popd
on_success:
  put:  git-pull-requests
  params:
    path: git-pull-requests
    status: success
on_failure:
  put:  git-pull-requests
  params:
    path: git-pull-requests
    status: failure
